### ISSUE TITLE
CUDA out of memory when run methods PLOP/POD/MIB 

### ISSUE THREAD

**Issue by vivian-2727** [MECLabTUDA/Lifelong-nnUNet#3]
My training commands are as follows:
```
[PLOP] nnUNet_train_plop 2d -t 71 72 73 74 75 76 -f 0 -pod_lambda 0.01 -num_epoch 250 -d 0 -save_interval 25 -s seg_outputs --store_csv
[POD] nnUNet_train_pod 2d -t 71 72 73 74 75 76 -f 0 -pod_lambda 0.01 -num_epoch 250 -d 0 -save_interval 25 -s seg_outputs --store_csv
[MIB] nnUNet_train_mib 2d -t 71 72 73 74 75 76 -f 0 -mib_lkd 31 -num_epoch 250 -d 0 -save_interval 25 -s seg_outputs --store_csv
```

**Specifically,  the MIB training process breaks off when it just finished 250 epoches on task 71 and try to begin training on task72.
The POD and PLOP training processes break off aftere they finish 25 epoches(save checkpoints and validate) on task71 and try to begin train the 26th epoch.**

When I try to run methods of PLOP/POD/MIB, CUDA out of memory error occured. And the error message when I run POD is shown as follow:
(I have tried different devices including 2080Ti and 3090, but the same error occurs.)

```
2022-08-07 13:16:50.407931:
epoch:  25
Epoch 26/250:   0%|                                                                                                                            | 0/250 [00:00<?, ?it/s]
using pin_memory on device 0
Epoch 26/250:   0%|                                                                                                                            | 0/250 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nnunet/bin/nnUNet_train_pod", line 33, in <module>
    sys.exit(load_entry_point('nnunet-ext', 'console_scripts', 'nnUNet_train_pod')())
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/run/run_training.py", line 979, in main_pod
    run_training(extension='pod')
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/run/run_training.py", line 852, in run_training
    
run_training(extension='pod')                                                                                               
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/run/run_training.py", line 852, in run_training
    trainer.run_training(task=t, output_folder=output_folder_name)
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/training/network_training/pod/nnUNetTrainerPOD.py", line 83, in run_training
    ret = super(nnUNetTrainerPLOP, self).run_training(task, output_folder)
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/training/network_training/multihead/nnUNetTrainerMultiHead.py", line 561, in run_training
    ret = super().run_training()
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
    trainer.run_training(task=t, output_folder=output_folder_name)                                                          
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/training/network_training/pod/nnUNetTrainerPOD.py", line 83, in run_training
    ret = super(nnUNetTrainerPLOP, self).run_training(task, output_folder)
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/training/network_training/multihead/nnUNetTrainerMultiHead.py", line 561, in run_training
    ret = super().run_training()
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/training/network_training/network_trainer.py", line 450, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/training/network_training/pod/nnUNetTrainerPOD.py", line 93, in run_iteration
    loss = super().run_iteration(data_generator, do_backprop, run_online_evaluation, detach, no_loss, pod=True)
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/training/network_training/plop/nnUNetTrainerPLOP.py", line 227, in run_iteration
    loss = super().run_iteration(data_generator, do_backprop, run_online_evaluation, detach, no_loss)
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/training/network_training/multihead/nnUNetTrainerMultiHead.py", line 612, in run_iteration    output = self.network(data)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/network_architecture/generic_UNet.py", line 401, in forward
    x = self.conv_blocks_localization[u](x)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/network_architecture/generic_UNet.py", line 142, in forward
    return self.blocks(x)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/training/network_training/network_trainer.py", line 450, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/training/network_training/pod/nnUNetTrainerPOD.py", line 93, in run_iteration
    loss = super().run_iteration(data_generator, do_backprop, run_online_evaluation, detach, no_loss, pod=True)
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/training/network_training/plop/nnUNetTrainerPLOP.py", line 227, in run_iteration
    loss = super().run_iteration(data_generator, do_backprop, run_online_evaluation, detach, no_loss)
  File "/home/ubuntu/Workspace/zww/nnUNetFrame/nnUNet-continual/nnunet_ext/training/network_training/multihead/nnUNetTrainerMultiHead.py", line 612, in run_iteration    output = self.network(data)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/network_architecture/generic_UNet.py", line 401, in forward
    x = self.conv_blocks_localization[u](x)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/network_architecture/generic_UNet.py", line 142, in forward
    return self.blocks(x)

    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/network_architecture/generic_UNet.py", line 142, in forward
    return self.blocks(x)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/network_architecture/generic_UNet.py", line 68, in forward
    return self.lrelu(self.instnorm(x))
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/instancenorm.py", line 57, in forward
    return F.instance_norm(
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/functional.py", line 2327, in instance_norm
    return torch.instance_norm(
RuntimeError: CUDA out of memory. Tried to allocate 226.00 MiB (GPU 0; 10.76 GiB total capacity; 9.13 GiB already allocated; 33.69 MiB free; 9.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.

```

**Comment by amrane99** [comment]
Hey,

so the _CUDA OOM error_ occurs since the program **tried to allocate 226.00 MiB (GPU 0; 10.76 GiB total capacity; 9.13 GiB already allocated; 33.69 MiB free; 9.26 GiB reserved in total by PyTorch)** and there is only 33.69 MiB memory left on your GPU during runtime. So this actually means that the network is too big for your GPU:

- On what type of data exactly are you training (Prostate, Heart, Brain MRI) ?
- Did you also test to train with the _3d_fullres_ setup instead of _2d_, as the network might not allocate that much memory in a 3D setup ?
- Did you train with a sequential training process and encountered the same CUDA OOM error ?

The Lifelong nnU-Net is built on top of the nnU-Net Framework and thus builds the network specifically based on the first task in your task list, i.e. 71. So my first suggestion would be to test if you can successfully train sequentially (without any CL method), i.e. using only the sequential training method for your 6 tasks [nnUNet_train_sequential]. If the network does not fit on your GPU, you will encounter the same CUDA OOM issue when training sequentially.

Another aspect I want to mention is that PLOP, POD and MiB are very memory intensive methods as they are Knowledge Distillation based methods. So during runtime the previously trained network (trained on task 1 until i-1) _and_ the current network (trained on task 1 until i) are used in tandem. So if one network does not fit on a single GPU when training in a sequential order, the PLOP, POD and MiB networks won't fit either. That's why I would suggest you before using any CL method to test if the sequential training process successfully runs on your GPU as its the easiest one. If you get an CUDA OOM error for the sequential training, then the generated network is too large for your GPU and no CL method will work as they only need more memory during runtime, not less :)
