### ISSUE TITLE
PackageNotFoundError: nnunet-ext

### ISSUE THREAD

**Issue by GhostDragon124** [MECLabTUDA/Lifelong-nnUNet#5]
Dear MECLab.

I'm trying to run a  training for PLOP method according to your offcial document, however, I keep encountered errors. I wonder is there anything I did wrong? I successfully installed the framework and passed all 4 test. Really thanks you guys' contribution!

Here is the errors, I met:

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================= 4 passed, 28 warnings in 2373.66s (0:39:33) =================================================

So, the installation is correct

(env) root@autodl-container-6f1911bc52-29abf360:~/autodl-tmp/Lifelong-nnUNet# nnUNet_train_plop 3d_fullres -t 11 12 13 -f 0 -pod_lambda 0.01 -num_epoch 250 -d 0 -save_interval 25 -s seg_outputs --store_csv
Traceback (most recent call last):
  File "/root/miniconda3/envs/env/bin/nnUNet_train_plop", line 33, in <module>
    sys.exit(load_entry_point('nnunet-ext', 'console_scripts', 'nnUNet_train_plop')())
  File "/root/miniconda3/envs/env/bin/nnUNet_train_plop", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/root/miniconda3/envs/env/lib/python3.9/importlib/metadata.py", line 542, in distribution
    return Distribution.from_name(distribution_name)
  File "/root/miniconda3/envs/env/lib/python3.9/importlib/metadata.py", line 196, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: nnunet-ext

I tried to install this package, but failed:

(env) root@autodl-container-6f1911bc52-29abf360:~/autodl-tmp/Lifelong-nnUNet# pip install nnunet-ext
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement nnunet-ext (from versions: none)
ERROR: No matching distribution found for nnunet-ext

**Comment by GhostDragon124** [comment]
I solved it by run setup.py
