### ISSUE TITLE
Issue about how the framework found the training dataset

### ISSUE THREAD

**Issue by GhostDragon124** [MECLabTUDA/Lifelong-nnUNet#6]
Dear author, thank you for opening source this framework. I meet a problem when I train the plop method. Here is the command type: nnUNet_train_plop 3d_fullres -t 2 4 -f 0 -pod_lambda 0.01 -num_epoch 25 -d 0 -save_interval 25 -s seg_outputs --store_c

I already put the Task02_Heart, and Task04_Hippocampus datasets into the "nnUNet_raw_data" folder, but the framework still cannot find the dataset. I also checked the environment variable setting, and my setup also passed all the pytest testing tasks. Really thank you for your help.

**Comment by GhostDragon124** [comment]
This is the error I meet:

(env) root@autodl-container-6f1911bc52-29abf360:~/autodl-tmp/Lifelong-nnUNet# nnUNet_train_plop 3d_fullres -t 04 -f 0 -pod_lambda 0.01 -num_epoch 25 -d 0 -save_interval 25 -s seg_outputs --store_csv


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

/root/autodl-tmp/Lifelong-nnUNet/nnunet_ext/run/run_training.py:274: UserWarning: When training on only one task, the conventional training of the nnU-Net can be used.
  warnings.warn("When training on only one task, the conventional training of the nnU-Net can be used.")
Traceback (most recent call last):
  File "/root/miniconda3/envs/env/bin/nnUNet_train_plop", line 33, in <module>
    sys.exit(load_entry_point('nnunet-ext==0.0.0', 'console_scripts', 'nnUNet_train_plop')())
  File "/root/autodl-tmp/Lifelong-nnUNet/nnunet_ext/run/run_training.py", line 982, in main_plop
    run_training(extension='plop')
  File "/root/autodl-tmp/Lifelong-nnUNet/nnunet_ext/run/run_training.py", line 492, in run_training
    t = convert_id_to_task_name(task_id)
  File "/root/miniconda3/envs/env/lib/python3.9/site-packages/nnunet/utilities/task_name_id_conversion.py", line 51, in convert_id_to_task_name
    raise RuntimeError("Could not find a task with the ID %d. Make sure the requested task ID exists and that "
RuntimeError: Could not find a task with the ID 4. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=nnUNet_preprocessed
RESULTS_FOLDER=~nnUNet_results
nnUNet_raw_data_base=nnUNet_data_base
If something is not right, adapt your environemnt variables.

**Comment by GhostDragon124** [comment]
Thank you for sharing this framework. I have successfully run it. The solution is that I have to use "nnUNet_plan_and_preprocess -t 002 --verify_dataset_integrity" to pre-processing the dataset.
